### PR TITLE
Add dockerfile to contrib

### PR DESCRIPTION
**Pull request by zero323**

### CODE REVIEW

**Comment by smassung** [comment]
Thanks for switching branches and using contrib/

**Comment by zero323** [comment]
My pleasure.

It could be useful to replace [image on Docker Hub](https://registry.hub.docker.com/u/zero323/meta/) as well. It is straightforward process (it is enough to fill in branch and path) but to use automated builds it has to be done by someone who is a member of the organization.

**Comment by smassung** [comment]
Sorry for the delay, I've just created the docker account. Could you tell me where specifically I need to add the branch and path? Thanks!

**Comment by zero323** [comment]
First you have to click on Add Repository and choose Automated Build:

automated

After that there are some screen where you select service and repository and final configuration page. If you replace Repo Name it should look like this:

automated_2

**Comment by smassung** [comment]
Thanks for the explanation! Here's the output of the last build (on develop): https://registry.hub.docker.com/u/smassung/meta/build_id/49907/code/bnjxsowzbmtmwqskw98y7vv/

Once we merge for v1.3.4, I can add one for the master branch as well.

**Pull request merged**
