### PR TITLE
create include/hashing/ directory

### PR DESCRIPTION
**Pull request by smassung**

### CODE REVIEW

**Comment by smassung** [comment]
There shouldn't be conflicts

**Comment by skystrife** [comment]
Should we maybe move this to a separate namespace (like `meta::hashing` or `meta::hash`)?

**Comment by smassung** [comment]
Yes, I should remove `util` and use a different namespace name.

**Comment by smassung** [comment]
@skystrife , can you restart the build?

**Comment by skystrife** [comment]
Just merged this manually, as the Appveyor tests failing is a separate issue not related to these changes anyway.

**Pull request merged**
