### PR TITLE
Use sarray in feature_selector

### PR DESCRIPTION
**Pull request by skystrife**
See the discussion in #111. This simplifies the creation of a feature-selected `dataset` that uses contiguous `feature_id`s. It should also use less disk space for storing the selected features (but I doubt that is all that important).

### CODE REVIEW

**Comment by smassung** [comment]
No other issues aside from adding comment to `selected()`. :+1:

**Comment by skystrife** [comment]
(Derp, I deleted the branch before this was merged...)

**Comment by skystrife** [comment]
(Derp, I deleted the branch before this was merged...)

**Comment by skystrife** [comment]
Pretty sure that last build got hung up. I think it's finishing now.

**Comment by smassung** [comment]
LGTM

**Pull request merged**
