### PR TITLE
Documentation Fixes

### PR DESCRIPTION
**Pull request by skystrife**
This PR addresses issue #52 by adding detailed setup guides for OS X, the two currently supported LTS versions of Ubuntu, and Arch Linux (because why not).

I tested everything on my local system using docker to get the different versions of Ubuntu, and booted my laptop into OS X v10.9 for the OS X instructions. They seem to be correct from those tests, and with the latest changes in develop I can easily run the unit tests on all three (everything passes).

I ended up not really saying much about selecting your compiler since the reality is that each system sort of has its own "best compiler" with the exception of Arch (for whom I doubt an install guide is even really necessary).

### CODE REVIEW

**Comment by skystrife** [comment]
Assigning @smassung mainly for proofreading and other comments/suggestions. Feel free to merge if you think it's ready, or suggest changes I can make before it's mergable.

**Comment by skystrife** [comment]
Should I add a guide for EWS/EngrIT-managed systems, since we might expect some UIUC users?

**Comment by smassung** [comment]
Yes, EWS guide would be great

**Comment by skystrife** [comment]
Added.

**Comment by smassung** [comment]
Can confirm EWS guide works on that system

**Pull request merged**
