### PR TITLE
ctest error fix

### PR DESCRIPTION
**Pull request by CanoeFZH**
As you see, just a change of method ```getUS()``` from ```getDefault()```. If this does not help, just ignore this and I will cancel it.

### CODE REVIEW

**Comment by smassung** [comment]
I'll leave this one to @skystrife to merge, since he is the one that did the investigation. Looks good to me though, thanks!

**Comment by smassung** [comment]
Now that I see this again, please put the pull request on the develop branch. We only update master for releases. Thanks!

**Comment by skystrife** [comment]
Actually, I think this is important enough to pull into master and merge into develop.

I'll get to this in a bit...

**Comment by smassung** [comment]
Sure thing. Do we want to make a new version including this though? If we don't, I'm assuming the MOOC students will still have the issue unless the version number is bumped in any instructions.

**Comment by skystrife** [comment]
Yeah, I'll push a 1.3.7 tag as well. The MOOC instructions (or even just a sticky in their forum) can then direct them to use the tip of master or the 1.3.7 tag.

**Comment by skystrife** [comment]
OK, this is "merged" in 547d0456. Non-traditional merge since I rewrote the commit message to be more descriptive about why the change was made. I think I managed to do it while still giving you credit for the commit (you should set up your email in your git client, btw).

**Comment by CanoeFZH** [comment]
Haha, thank you. Thank you for you great work of META!

**Pull request closed without merging**
